### ISSUE TITLE
Icon links doing interesting things

### ISSUE THREAD

**Issue by ihsan314** [mmurray22/my-portfolio#16]
I noticed that the GitHub icon on the homepage linked to your LinkedIn profile, and that the LinkedIn icon linked to your email.

**Comment by mmurray22** [comment]
Hi Ihsan! Thanks for pointing that out! I fixed that on a different branch and forgot to update the branch I’m currently hosting the site from. I’ll fix it in the next couple hours :)

**Comment by mmurray22** [comment]
Resolved!
